version: '3.8'
services:
  db:
    image: postgres:rentcar
    container_name: rentcar-dev
    build: ./Images/Postgresql
    restart: always
    environment: 
      POSTGRES_PASSWORD: "secretworld"
    ports:
      - "5432:5432"

  # flyway:
  #   image: flyway/flyway:latest
  #   container_name: flyway
  #   build: ./Images/Flyway
  #   command: -url=jdbc:postgresql://172.30.222.82:5432/rcdev1 -user=rcuser -password=secretpassword -connectRetries=60 migrate
  #   volumes: 
  #   - ./data:/flyway/sql
  #   depends_on:
  #     - db

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    depends_on: 
      - db

volumes: 
  pgadmin-data:
  
